on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-20.04
    # Permissions to use OIDC token authentication
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        with:
          project: sHdQRWUGI6
          context: .
